### ISSUE TITLE
The bar width of 'other' language may overflow in the most used language card

### ISSUE THREAD

**Issue by hakula139** [avgupta456/github-trends#153]
It seems that the bar width of 'Other' language may overflow if its number of lines is greater than the most used language above. See [here](https://api.githubtrends.io/user/svg/hakula139/langs?time_range=one_year&include_private=true&theme=dark) for an example.

![GitHub Trends](https://api.githubtrends.io/user/svg/hakula139/langs?time_range=one_year&include_private=true&theme=dark)

Also, is it possible to display more languages by providing an optional argument to the API (like `langs_count` in [github-readme-stats](https://github.com/anuraghazra/github-readme-stats#top-languages-card))? Great thanks!

**Comment by avgupta456** [comment]
Thank you for using GitHub Trends and filing this issue. I should be able to fix the overflowing row in the next couple of days. Adding a `lang_count` flag is a good idea, but it might take a bit longer to address. I will keep you updated on this thread.

**Comment by avgupta456** [comment]
#155 resolves the first half of this ticket. I validated your card looks better now. I will close this issue and create a separate one to track adding a `lang_count` flag.
