### ISSUE TITLE
Add full time period as an option

### ISSUE THREAD

**Issue by vycdev** [avgupta456/github-trends#159]
Right now the biggest time period you can select is one year, it would be nice if there was an option to see the stats for the languages and repositories from the moment you created your github account until the present.

**Comment by OrangoMango** [comment]
Yeah this feature is really missing

**Comment by avgupta456** [comment]
This is finally implemented! Check it out on the website, and note it may take a couple minutes to fetch all your data the first time. Let me know if you run into any issues.
