### ISSUE TITLE
Small Talk in Languages When enabled private 

### ISSUE THREAD

**Issue by saivineeth100** [avgupta456/github-trends#160]
I don't have any repositories that has **Smalltalk language**(I never heard also)
But it is listed under my language stats

**languages I work on**

- C#
- Python
- Typescript/JavaScript
- sass/CSS
- HTML5

[![GitHub Trends SVG](https://api.githubtrends.io/user/svg/saivineeth100/langs?time_range=one_year&include_private=True&theme=classic)](https://githubtrends.io)

**Comment by avgupta456** [comment]
Hello, thank you for bringing this issue up. The extension map JSON I am using routed ".cs" file extensions to a language called SmallTalk (I had not heard of it either). I updated this to route to C# now. Let me know if the problem persists (it might take up to a day to clear the cache).

**Comment by saivineeth100** [comment]
@avgupta456  Now working **Fine** , Thank you for resolving fast
