### ISSUE TITLE
Is the API server down?

### ISSUE THREAD

**Issue by hakula139** [avgupta456/github-trends#162]
Visit <https://api.githubtrends.io/user/svg/hakula139/langs> for instance, and we will encounter a 500 error.

```text
Error: Server Error
The server encountered an error and could not complete your request.
Please try again in 30 seconds.
```

**Comment by avgupta456** [comment]
Thank you for opening this issue. I believe the error was due to a cloud billing issue, which has been resolved. The endpoint you listed seems to be working again for me. Feel free to reopen if you notice any lingering issues.

**Comment by hakula139** [comment]
Seems to occur again 👀

**Comment by avgupta456** [comment]
Thanks for the ping, should be resolved now. I believe this was due to a user deleting their GitHub account. I am tracking the issue here: https://github.com/avgupta456/github-trends/issues/171
