### ISSUE TITLE
Add to profile link sometimes wrong

### ISSUE THREAD

**Issue by MolotovCherry** [avgupta456/github-trends#168]
The add to profile link is sometimes incorrect, as the main repository may have a different branch name. In this case, mine was named "main", and the link was looking for "master"

![image](https://user-images.githubusercontent.com/13651622/163083966-c7a86c7b-f341-4100-8820-62e2a7119aff.png)

**Comment by yansheng836** [comment]
When I click on it, it doesn't seem to bring the corresponding information. Is that because I already have a file?

![image](https://user-images.githubusercontent.com/45334066/164908915-7dc18de2-16d3-4aea-9d35-d7d7857a0cec.png)

**Comment by avgupta456** [comment]
It should be copied to your clipboard. I will eventually replace the automatic redirect with a pop-up that explains the process with relevant links.
