### ISSUE TITLE
Star Bug and workaround

### ISSUE THREAD

**Issue by darkpixel** [avgupta456/github-trends#218]
Bug: The app won't run unless you star the ```github-trends``` repo in a shameless bid to get stars.

Workaround: Star the repo, run the app, then unstar the repo.

**Comment by avgupta456** [comment]
I'm sorry you feel that way, I need this feature to prevent spam requests and stay within the Github GraphQL API rate limit. You are completely free to star the repo, run the app, then unstar the repo. This is explicitly mentioned on the Wrapped landing page already. Alternatively, users can create an account with GitHub Trends to use their own personal GitHub token. In this scenario, you are not required to star the repo. I am closing this issue as I do not view it as a bug.
