### ISSUE TITLE
Application signup should not request write access to my repos

### ISSUE THREAD

**Issue by franzwilhelm** [avgupta456/github-trends#219]
To get private github trends i now must accept that you get write access to my repos. That is not something I'm comfortable allowing. Can it be disabled and only allow read access?

**Comment by avgupta456** [comment]
Unfortuantely, GitHub only allows granting either no private access, or full read/write: https://docs.github.com/en/developers/apps/building-oauth-apps/scopes-for-oauth-apps#available-scopes. 

I completely understand the concerns/risks in giving write access, but sadly I have no workaround at this time.
