### ISSUE TITLE
Allow switching styles or versions

### ISSUE THREAD

**Issue by wll8** [avgupta456/github-trends#222]
This is an image from last year, I love the style, but I can't find a way to use it now.
![微信图片_20221219134121](https://user-images.githubusercontent.com/28223260/208356216-50f9dc6b-0382-4807-a501-01314cec9e8f.jpg)

Using the same style makes it easier to compare changes over the two years.

It doesn't make sense to show a contribution graph for 2023 when it's only 2022.
![image](https://user-images.githubusercontent.com/28223260/208356098-0d46dfc7-23f6-4e41-8f81-67ae76925864.png)

**Comment by avgupta456** [comment]
@wll8 thanks for the feedback. I believe the double calendar issue is a timezone bug, I just pushed a fix. Could you let me know if it looks better on your end now?

Regarding the changed style, I can look into more styling options and allowing for easier comparison to previous years. 
I will create a separate issue to track that request, and we can use this issue for the double calendar fix. 

In the meantime, you can find your previous GitHub Wrapped by appending a `/2021` to the URL: https://www.githubtrends.io/wrapped/wll8/2021.
