### ISSUE TITLE
fix: Should not display an interactive button when saving an image

### ISSUE THREAD

**Issue by wll8** [avgupta456/github-trends#227]
In fact, as pictures, these interactive buttons or text are meaningless.

![image](https://user-images.githubusercontent.com/28223260/208570427-c4abf594-2eb5-4302-bb64-920c16a5066f.png)

**Comment by avgupta456** [comment]
Great suggestion, I should be able to push a fix soon. The bottom referral link is intentional but can be easily cropped out.

**Comment by avgupta456** [comment]
Sorry for the (extremely) long delay, but I just pushed a fix. I hope you use Github Trends this year!
