### ISSUE TITLE
FAQ or other docs should describe how to run the code locally

### ISSUE THREAD

**Issue by JasonGross** [avgupta456/github-trends#230]
I'd like to get the language stats on my machine, without handing my OAuth token to github-trends.  Can I reuse the code in this repo somehow?  Is there a python script I can just run?  (This would also allow working around #159.)

**Comment by avgupta456** [comment]
Good idea, will add docs for local development soon.

**Comment by avgupta456** [comment]
Sorry for the long delay, I updated the FAQ with instructions. Essentially, you can clone the repository, install the backend dependencies and then run the following script:

```bash
python ./scripts/local.py --user_id=USER_ID --access_token=ACCESS_TOKEN --start_date=2023-01-01 --end_date=2023-01-31 --output_dir=OUTPUT_DIR
```

Let me know if you need any additional clarification
