### ISSUE TITLE
GitHub Wrapped Error

### ISSUE THREAD

**Issue by jnmunene** [avgupta456/github-trends#268]
I am getting this error when I try to get my wrapped: "Something went wrong. Please try again in a couple minutes or raise an issue on [GitHub](https://github.com/avgupta456/github-trends/issues/new). Thank you!"

**Comment by agentcobra** [comment]
Same issue for me :

HTTP 500 https://api.githubtrends.io/wrapped/agentcobra?year=2023
```js
{"data":[],"message":"Error you are over your space quota, using 512 MB of 512 MB, full error: {'ok': 0, 'errmsg': 'you are over your space quota, using 512 MB of 512 MB', 'code': 8000, 'codeName': 'AtlasError'}","time":"PT1.722084S"}```

**Comment by avgupta456** [comment]
So sorry about that, it should be fixed now. Please try again and let me know if you run into any difficulties!
