### ISSUE TITLE
[BUG] GitHub Wrapped doesn't work for me

### ISSUE THREAD

**Issue by Rishi-Sudhakar** [avgupta456/github-trends#292]
"Something went wrong. Please try again in a couple minutes or raise an issue on [GitHub](https://github.com/avgupta456/github-trends/issues/new). Thank you!"

<img width="1376" alt="Screenshot 2024-06-23 at 12 19 19 AM" src="https://github.com/avgupta456/github-trends/assets/79398572/da59a350-947f-40fa-8174-6eea981bf1d3">

I've signed in properly, you can see the right corner, starred the repo, my username was correct, I gave access to both private and public repos.

**Comment by avgupta456** [comment]
https://www.githubwrapped.io/Rishi-Sudhakar

It's working for me, is it working for you?
