### ISSUE TITLE
GitHub Wrapped is not working for me :(

### ISSUE THREAD

**Issue by DevGoyalG** [avgupta456/github-trends#294]
![Screenshot 2024-07-23 220218](https://github.com/user-attachments/assets/cf5c87b3-1faf-449b-a4d6-bebe928c62ca)

**Comment by avgupta456** [comment]
It's working for me. Is it working for you now?

https://www.githubwrapped.io/DevGoyalG

**Comment by DevGoyalG** [comment]
Yes! It is working for me now!!

Thank you :)
