### ISSUE TITLE
Github-Wrapped_Problem

### ISSUE THREAD

**Issue by Subhamoy-Saha-100** [avgupta456/github-trends#304]
![WhatsApp Image 2024-12-18 at 10 32 01_f0b7e323](https://github.com/user-attachments/assets/6ad5dc73-0dc9-4cad-8496-053e44363fe9)

**Comment by LRGuess** [comment]
Same here...

**Comment by Jayden295** [comment]
Same for me...

**Comment by lewxdev** [comment]
I'm seeing this from the network tab of dev tools:

```jsonc
// 20241220133344
// https://api.githubtrends.io/wrapped/lewxdev?year=2024

{
  "data": [],
  "message": "Error you are over your space quota, using 512 MB of 512 MB, full error: {'ok': 0, 'errmsg': 'you are over your space quota, using 512 MB of 512 MB', 'code': 8000, 'codeName': 'AtlasError'}",
  "time": "PT4.34957S"
}
```

**Comment by avgupta456** [comment]
https://www.githubwrapped.io/Subhamoy-Saha-100
https://www.githubwrapped.io/LRGuess
https://www.githubwrapped.io/Jayden295
https://www.githubwrapped.io/lewxdev

Should be working now. Let me know if the issue persists.
