### ISSUE TITLE
Something went wrong

### ISSUE THREAD

**Issue by josema294** [avgupta456/github-trends#339]
Service not working at all, I've been waiting and trying again, but apparently still crashing:

![2024-12-26_20-48](https://github.com/user-attachments/assets/ba7db037-975e-4ff6-9676-bbeb150ee14f)
Thanks in advance for your time
josema294

**Comment by avgupta456** [comment]
It should be working now: https://www.githubwrapped.io/josema294. Let me know if the issue persists.
