### ISSUE TITLE
GitHub Wrapped (Something went wrong)

### ISSUE THREAD

**Issue by DonCrafts1** [avgupta456/github-trends#341]
When trying to view GitHub Wrapped, after entering my username and waiting a while on loading screen, it shows:
"Something went wrong. Please try again in a couple minutes or raise an issue on GitHub. Thank you!".

I have repeated the process multiple times.

**Comment by avgupta456** [comment]
It should be fixed now: https://www.githubwrapped.io/DonCrafts1. Let me know if the issue persists.
