### ISSUE TITLE
unable to create wrapped

### ISSUE THREAD

**Issue by Ramesh0708** [avgupta456/github-trends#344]

**Comment by ArnabDeepNath** [comment]
{"data":[],"message":"Error you are over your space quota, using 512 MB of 512 MB, full error: {'ok': 0, 'errmsg': 'you are over your space quota, using 512 MB of 512 MB', 'code': 8000, 'codeName': 'AtlasError'}","time":"PT12.001342S"}


This might be case

**Comment by ArnabDeepNath** [comment]
This was coming in one of the response from the api where it is firing to get the wrapped

**Comment by avgupta456** [comment]
https://www.githubwrapped.io/Ramesh0708
https://www.githubwrapped.io/ArnabDeepNath

Let me know if these are still not working.
