### ISSUE TITLE
Error when generating 2024 GitHub Wrapped statistics

### ISSUE THREAD

**Issue by Rashad-omran** [avgupta456/github-trends#345]
I encountered an issue while trying to generate my 2024 GitHub Wrapped statistics. The website displayed the following error message:
Something went wrong. Please try again in a couple of minutes or raise an issue on GitHub.

**Comment by kiki0124** [comment]
I also got this, seems like the api returned 500
 ![image](https://github.com/user-attachments/assets/1375fec8-895c-4960-8495-94a3bc9d0e30)

**Comment by hugs7** [comment]
The response I get is 
```
{
    "data": [],
    "message": "Error you are over your space quota, using 512 MB of 512 MB, full error: {'ok': 0, 'errmsg': 'you are over your space quota, using 512 MB of 512 MB', 'code': 8000, 'codeName': 'AtlasError'}",
    "time": "PT1.829915S"
}
```

Looks like a quota issue

**Comment by LESS14** [comment]
Also got the same issue, when I open the API request 

The response I get is the same as above: 

`{"data":[],"message":"Error you are over your space quota, using 512 MB of 512 MB, full error: {'ok': 0, 'errmsg': 'you are over your space quota, using 512 MB of 512 MB', 'code': 8000, 'codeName': 'AtlasError'}","time":"PT1.397845S"}`

**Comment by avgupta456** [comment]
https://www.githubwrapped.io/Rashad-omran
https://www.githubwrapped.io/kiki0124
https://www.githubwrapped.io/hugs7
https://www.githubwrapped.io/LESS14

Let me know if these are still not working.

**Comment by hugs7** [comment]
> Let me know if these are still not working.

Still down for me![Screenshot_20241230_154349_Chrome.jpg](https://github.com/user-attachments/assets/05e421fe-f777-477d-949c-729c5dfbe8c7)
