### ISSUE TITLE
data not showing

### ISSUE THREAD

**Issue by MansuriTamim** [avgupta456/github-trends#346]
I recently try to see my github  wrapped but i try many times but the data is not coming 
https://github.com/user-attachments/assets/f467dc82-48ae-43cf-89e4-ced41c3f1c10

**Comment by leohonlmc** [comment]
Same here

**Comment by avgupta456** [comment]
https://www.githubwrapped.io/MansuriTamim
https://www.githubwrapped.io/leohonlmc

Let me know if these are not working still.
