### ISSUE TITLE
Something went wrong. Please try again in a couple of minutes

### ISSUE THREAD

**Issue by Abdullah-Niaz** [avgupta456/github-trends#351]
While using the website, I encountered an error message:
"Something went wrong. Please try again in a couple of minutes or raise an issue on GitHub. Thank you!"
This error prevents me from using the site.

**Additional:**  This issue occurs every time I visit the site, regardless of refreshing or clearing my cache. I have also tried accessing the site from different devices and browsers, but the error persists.

**Comment by avgupta456** [comment]
Your contribution history is private so you wrapped is empty: https://www.githubwrapped.io/Abdullah-Niaz
