### ISSUE TITLE
Update Readme

### ISSUE THREAD

**Issue by avgupta456** [avgupta456/github-trends#53]

**Comment by akashprasher** [comment]
Hey, @avgupta456
You're having good repo but the Issues posted by you lack a description. Please provide some details so that someone can contribute.

**Comment by avgupta456** [comment]
Thanks for the feedback. I'm currently using these issues to keep track of tasks for myself, but let me know if you (or anyone else) would be interested in contributing, and I can prioritize adding more documentation.
